function result = api_user_options()
% Common options to use across FusionTwin.io API calls:
    result = struct(...
        'backend_url', 'https://api.fusiontwin.dev', ...
        'api_key', '<enter-your-api-key>', ...
        'workspace_id', '<enter-your-workspace-id>', ...
        'twin_key', 'd3d2024', ...
        'simulator_key', 'NSFS');
end